version: '3.8'
services:
  nest-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest
    networks:
      - nest-pgsql
  test-db:
    image: postgres:13
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nest
    networks:
      - nest-pgsql
networks:
  nest-pgsql: